### ISSUE TITLE
Other languages support

### ISSUE THREAD

**Issue by Teelve** [zwacky/pokedex-go#1]
Add more languages :) I can translate it to French if you need help

**Comment by zwacky** [comment]
that's a great idea. a language object of different locale and their names.

what would help the most is to have a source of different pokemon names.

**Comment by Teelve** [comment]
http://pokewiki.de/Pok%C3%A9mon-Liste

Found this, you have German, French, English, Japanese and Korean. That's a start

**Comment by zwacky** [comment]
very nice, easily scrapable for these languages 👍

**Comment by dmehala** [comment]
It's exactly what I am working on. Right now my implementation just parse the message and look for a correspondence in any other languages. Then passed the english name to sendPokemonDetail. Any advise ?

**Comment by zwacky** [comment]
the pokemon.json would need to have a `alternateNames` property:

```
"alternateNames": {
    "en": "Bulbasaur",
    "de": "Bisasam",
    ...
}
```

and here the search needs to be done over all these names it would need to be done here https://github.com/zwacky/pokedex-go/blob/master/src/database-manager.js#L22

```
_(DB.POKEMONS)
    .filter(pkmn => {
        return _(pkmn.alternateNames)
            .filter((entry, key) => entry === pokemonName)
            .value()
            .length !== 0;
    })
    .first();
```

**Comment by dmehala** [comment]
I made a json with alternate name : https://gist.github.com/DamiX/503941daf16c73a746ac1a43b616326e

**Comment by zwacky** [comment]
sweet, @DamiX! will have a look at it later today

**Comment by zwacky** [comment]
with #2 we should have this covered.

if there are more sources for more languages like spanish or portuguese... keep 'em coming!
