### ISSUE TITLE
Moves in different languages

### ISSUE THREAD

**Issue by dmehala** [zwacky/pokedex-go#3]
I found this list of moves in other languages : http://bulbapedia.bulbagarden.net/wiki/List_of_moves_in_other_languages  

I can provide a json with alternate names as I did #2 . Are you agree ?

**Comment by zwacky** [comment]
Hey @DamiX, that is a great idea. The source seems complete and well listed!

On a side note: I'm now seeing new languages: Spanish and Italian. I couldn't find the Pokémon names in those languages. Maybe we could add those as well to be more complete.

**Comment by zwacky** [comment]
Thank you @DamiX, great work.

It's already partly included in the bot, only need to adjust the action buttons (e.g. `Best against x` and `Best moves of x`).

**Comment by zwacky** [comment]
The changes are fully live now and all tested. Thanks again @DamiX for your PR.
